export const MESSAGE_TYPE_LENGTH = 2;
export const VERSION_LENGTH = 1;
export const SEQUENCE_LENGTH = 4;
export const PAYLOAD_LENGTH = 4;

export const MessageType = {
  //
  MINI_GAME_JOIN_REQUEST: 1,
  MINI_GAME_MOVE_NOTIFICATION: 2,
  MINI_GAME_PLAYER_SPAWN_NOTIFICATION: 3,
  MINI_GAME_START_NOTIFICATION: 4,

  MINI_GAME_PLAYER_MOVE_REQUEST: 5,
  MINI_GAME_PLAYERS_STATE_SYNC_NOTIFICATION: 6,
  MINI_GAME_PLAYER_DEATH_NOTIFICATION: 7,
  MINI_GAME_MAP_STATE_SYNC_NOTIFICATION: 8,

  MINI_GAME_OVER_NOTIFICATION: 9,
};
